GP-1: This is a test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,37 +1,56 @@
-# This is a basic workflow to help you get started with Actions.
-
 name: CI
 
-# Controls when the action will run. 
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
+    branches: [ develop, test4 ]
   pull_request:
-    branches: [ master ]
+    branches: [ master, develop ]
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  install-and-cache:
+    if: ${{ github.event_name == 'pull_request' }}
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Setup NPM cache
+        uses: actions/cache@v2
+        id: npm-cache
+        with:
+          path: ./node_modules
+          key: ${{ hashFiles('**/package-lock.json') }}
+      - name: Install NPM Dependencies
+        if: steps.npm-cache.outputs.cache-hit != 'true'
+        run: npm install
+  check-branch-name:
+    if: ${{ github.event_name == 'pull_request' }}
+    needs: install-and-cache
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Check branch name
         run: |
-          ecsdfdsfho Add other actions to build,
-          echo test, and deploy your project.
-          sleep 30s
+          if [[ ! ${{ github.head_ref }} =~ ^(feature|release)\/GP-[0-9]+$ ]]; then
+              echo "::error::Invalid branch name"
+              exit 1
+          fi
+  check-branch-commit-messages:
+    if: ${{ github.event_name == 'pull_request' }}
+    needs: install-and-cache
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Fetch NPM cache
+        uses: actions/cache@v2
+        with:
+          path: ./node_modules
+          key: ${{ hashFiles('**/package-lock.json') }}
+      - name: Check branch commit messages
+        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
+
+  
+        
